name: segadb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - bcrypt=4.2.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cffi=1.17.1
  - colorama=0.4.6
  - cryptography=43.0.0
  - expat=2.6.3
  - freetype=2.12.1
  - joblib=1.4.2
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libdeflate=1.17
  - libexpat=2.6.3
  - libffi=3.4.4
  - libpng=1.6.39
  - libsqlite=3.47.2
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - pillow=10.4.0
  - pip=24.2
  - pycparser=2.21
  - python=3.12.3
  - python_abi=3.12
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tabulate=0.9.0
  - tk=8.6.14
  - tqdm=4.66.5
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - black==23.12.1
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - click==8.1.7
      - databind==4.5.2
      - databind-core==4.5.2
      - databind-json==4.5.2
      - deprecated==1.2.15
      - docspec==2.2.1
      - docspec-python==2.2.1
      - docstring-parser==0.11
      - idna==3.10
      - jinja2==3.1.4
      - markupsafe==3.0.2
      - mypy-extensions==1.0.0
      - nr-date==2.1.0
      - nr-stream==1.1.5
      - nr-util==0.8.12
      - packaging==24.2
      - pathspec==0.12.1
      - platformdirs==4.3.6
      - polars==1.17.1
      - pydoc-markdown==4.8.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - tomli==2.2.1
      - tomli-w==1.1.0
      - typeapi==2.2.3
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - watchdog==6.0.0
      - wrapt==1.17.0
      - yapf==0.43.0
