name: segadb_env2
channels:
  - conda-forge
  - defaults
dependencies:
  - bcrypt=4.2.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cffi=1.17.1
  - colorama=0.4.6
  - cryptography=43.0.0
  - expat=2.6.3
  - freetype=2.12.1
  - joblib=1.4.2
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libdeflate=1.17
  - libexpat=2.6.3
  - libffi=3.4.4
  - libpng=1.6.39
  - libsqlite=3.47.2
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - pillow=10.4.0
  - pip=24.2
  - pycparser=2.21
  - python=3.12.3
  - python_abi=3.12
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tabulate=0.9.0
  - tk=8.6.14
  - tqdm=4.66.5
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - polars==1.17.1

